server:
  port: 10013
spring:
  application:
    name: exam-user-service
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.onlineexam.pojo
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
#    aggressive-lazy-loading: false # 将积极加载改为消息加载即按需加载
#    lazy-loading-enabled: true # 开启懒加载