server:
  port: 10015
spring:
  application:
    name: exam-test-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/online_exam?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1
    hikari:
      max-lifetime: 28830000
      maximum-pool-size: 9
  servlet:
    multipart:
      max-file-size: 2MB
eureka:
  client:
    registry-fetch-interval-seconds: 5 #拉取服务的间隔时间5秒
    service-url:
      defaultZone: http://localhost:10010/eureka
  instance:
      lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
onlineexam:
  jwt:
    secret: onlineexam@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: ./jwt/rsa.pub
    priKeyPath: ./jwt/rsa.pri
    expire: 30 # 过期时间,单位分钟
    cookieName: TOKEN
mybatis:
  type-aliases-package: com.onlineexam.pojo
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名