server:
  port: 10015
spring:
  application:
    name: exam-test-service
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.onlineexam.pojo
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名