server:
  port: 10012

spring:
  application:
    name: exam-auth-service
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.onlineexam.pojo
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名